[package]
name = "TECHIT-FinalProject"
authors = ["Choigunwoo <gunwoo8873@outlook.kr"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]


[workspace]
members = [
    "./frontend",
    "./backend", "Kubernetes",
]
