[package]
name = "Kubernetes"
authors = ["Choigunwoo <gunwoo8873@outlook.kr"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = {version = "0.95.0", features = ["runtime", "derive"]}
k8s-openapi = {version = "0.23.0", features = ["latest"]}