name: backend-action.yml
on:
  push:
    branches: [ "backend/**" ]
    path: "backend/**"
  pull_request:
    branches: [ "backend/**" ]
    path: "backend/**"
  workflow_dispatch:

jobs:
  Linux-Build:
    runs-on: ubuntu-latest # Ubuntu 22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rustup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
          default: true